# TypeProf 0.21.2

# Classes
module Junoser
  class Ruler
    OFFSET: String
    @rule: String

    def initialize: (String input) -> void

    def to_rule: -> String
    def rule: -> String

    private

    def remove_comments: (String str) -> String
    def process_line: (String str) -> String
    def process_reserved_element: (String str) -> String
    def format: (Array[String?] | String str, ?String? offset) -> String
    def rule_header: -> String
    def rule_footer: -> String
  end
end
