#!/usr/bin/env ruby

require 'optparse'
require 'pathname'

$: << File.expand_path('../../lib', Pathname.new(__FILE__).realpath)
require 'junoser'


command = :apply
opts = OptionParser.new do |opts|
  opts.banner = 'junoser-apply: apply commands to config. (delete)'
  opts.define_head 'Usage: junoser-apply [path]'

  opts.on_tail '-h', '--help', 'Show this message' do
    puts opts
    exit
  end
end
opts.parse!
case command
  when :apply
    puts Junoser::Cli.apply($<)
  else
    puts opts
    abort
end
